#!/bin/bash
#
#  possible jenkins vars:
#      DOCKER_OS = Needs to be ubuntu-hirsuite

set -o errexit
set -o xtrace

export WORKDIR=$1

# ------------------------------------------------------------------------------
# Clone RocksDB for ZENFS compiling
# ------------------------------------------------------------------------------
pushd ${WORKDIR}
SOURCEDIR=${WORKDIR}/rocksdb-source

git clone --recursive https://github.com/percona-ysorokin/rocksdb.git -b percona_wdc rocksdb-source
popd

# ------------------------------------------------------------------------------
# compile ZENFS libs
# ------------------------------------------------------------------------------
pushd ${WORKDIR}/
mkdir ${WORKDIR}/rocksdb-root ${WORKDIR}/rocksdb-build

INSTALL_ROOT=${WORKDIR}/rocksdb-root
BUILD_ROOT=${WORKDIR}/rocksdb-build

pushd $SOURCEDIR
CC=clang-12 CXX=clang++-12 make DISABLE_WARNING_AS_ERROR=1 PREFIX=${INSTALL_ROOT}/usr OBJ_DIR=${BUILD_ROOT} ROCKSDB_PLUGINS=zenfs -j$(nproc) install-static
popd

pushd $SOURCEDIR/plugin/zenfs/util
PKG_CONFIG_PATH=$INSTALL_ROOT/usr/lib/pkgconfig make CC=clang-12 CXX=clang++-12 -j$(nproc)
popd

cp $SOURCEDIR/plugin/zenfs/util/zenfs ${WORKDIR}
rm -rf $INSTALL_ROOT $BUILD_ROOT $SOURCEDIR



