#!/bin/bash

set -o errexit
set -o xtrace


# ------------------------------------------------------------------------------
# Declare all input variables
# ------------------------------------------------------------------------------
JOB_CMAKE=${JOB_CMAKE:-cmake}
COMPILER=${COMPILER:-default}
CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:-RelWithDebInfo}
WITH_ROCKSDB=${WITH_ROCKSDB:-ON}
WITH_ROUTER=${WITH_ROUTER:-ON}
WITH_GCOV=${WITH_GCOV:-OFF}
WITH_MYSQLX=${WITH_MYSQLX:-ON}
WITH_JS_LANG=${WITH_JS_LANG:-OFF}
ANALYZER_OPTS=${ANALYZER_OPTS:-}
MAKE_OPTS=${MAKE_OPTS:--j$(grep -c ^processor /proc/cpuinfo)}
CMAKE_OPTS=${CMAKE_OPTS:-}
BUILD_COMMENT=${BUILD_COMMENT:-}
TAG=${TAG:-}
DIST_NAME=${DIST_NAME:-}
SSL_VER=${SSL_VER:-}
TARGET_CFLAGS=${TARGET_CFLAGS:-}

# ------------------------------------------------------------------------------
# set working dir
# ------------------------------------------------------------------------------
WORKDIR=$(cd ${1:-./build}; pwd -P)
BUILD_DIR=${WORKDIR}/build
INSTALL_DIR=${WORKDIR}/install
DOWNLOAD_DIR=${WORKDIR}/source_downloads

rm -rf ${INSTALL_DIR}
mkdir -p ${BUILD_DIR} ${INSTALL_DIR} ${DOWNLOAD_DIR}
SOURCEDIR=$(cd ${2:-$(dirname $0)/../sources}; pwd -P)

# ------------------------------------------------------------------------------
# get MySQL version
# ------------------------------------------------------------------------------
if [ -f $SOURCEDIR/VERSION ]; then
    source "$SOURCEDIR/VERSION"
elif [ -f $SOURCEDIR/MYSQL_VERSION ]; then
    source "$SOURCEDIR/MYSQL_VERSION"
else
    echo "NO VERSION file found"
    exit 1
fi
MYSQL_VERSION="$MYSQL_VERSION_MAJOR.$MYSQL_VERSION_MINOR.$MYSQL_VERSION_PATCH"

# ------------------------------------------------------------------------------
# Setup ccache if enabled
# ------------------------------------------------------------------------------
if [[ "${USE_CCACHE}" == "yes" ]]; then
    echo "Setting up ccache..."

    # Check if ccache is available
    if command -v ccache &> /dev/null; then
        ccache --version

        # Add ccache to CMake options
        CMAKE_OPTS="${CMAKE_OPTS} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache"

        # Show initial statistics
        echo "Initial ccache statistics:"
        ccache -s
    else
        echo "WARNING: ccache not found, continuing without cache"
        USE_CCACHE=0
    fi
fi


# ------------------------------------------------------------------------------
# download external libs
# ------------------------------------------------------------------------------
wget_loop() {
    local FILE="$1"
    local URL="$2"

    if [[ ! -f "${DOWNLOAD_DIR}/${FILE}" ]]; then
        until wget --progress=dot:giga -O "${DOWNLOAD_DIR}/${FILE}" "${URL}"; do
            echo "sleep before retry"
            sleep 1
        done
    fi
}

# Boost is not required for MySQL/PS 8.4.x or 9.y.z
if [[ "${MYSQL_VERSION}" == 8.0.* ]]; then
    BOOST_VERSION=$(grep 'SET(BOOST_PACKAGE_NAME' ${SOURCEDIR}/cmake/boost.cmake | sed -re 's/.*([0-9]+_[0-9]+_[0-9]+).*/\1/')
    wget_loop "boost_${BOOST_VERSION}.tar.bz2" "https://archives.boost.io/release/${BOOST_VERSION//_/.}/source/boost_${BOOST_VERSION}.tar.bz2"
fi

RHVER=0
if [[ -f /etc/redhat-release ]]; then
    RHVER="$(rpm --eval %rhel)"
fi

# ------------------------------------------------------------------------------
# Set OS/Arch flags
# ------------------------------------------------------------------------------
TARGET_ARCH="$(uname -m)"

# ------------------------------------------------------------------------------
# Set Debug options
# ------------------------------------------------------------------------------
if [[ "${CMAKE_BUILD_TYPE}" = "Debug" ]]; then
    BUILD_COMMENT+="-debug"
    CMAKE_OPTS+=" -DDEBUG_EXTNAME=OFF"
fi
if [[ "${ANALYZER_OPTS}" = *WITH_VALGRIND=ON* ]]; then
    BUILD_COMMENT+="-valgrind"
    CMAKE_OPTS+=" -DROCKSDB_DISABLE_MARCH_NATIVE=1"
fi

# ------------------------------------------------------------------------------
# set version
# ------------------------------------------------------------------------------
if [[ -n "$(which git)" ]] && [[ -d "$SOURCEDIR/.git" ]]; then
    REVISION="$(cd "$SOURCEDIR"; git rev-parse --short HEAD)"
fi
PERCONA_SERVER_VERSION="$(echo $MYSQL_VERSION_EXTRA | sed 's/^-//')"
PRODUCT="Percona-Server-$MYSQL_VERSION-$PERCONA_SERVER_VERSION"
PRODUCT_FULL="Percona-Server-${MYSQL_VERSION}-${PERCONA_SERVER_VERSION}${BUILD_COMMENT}-${TAG}$(uname -s)${DIST_NAME}.${TARGET_ARCH}${SSL_VER}"
COMMENT="Percona Server - GPL, Release ${MYSQL_VERSION_EXTRA#-}, Revision ${REVISION:-}${BUILD_COMMENT}"
printf >${WORKDIR}/build_info.txt "PRODUCT=${PRODUCT}\nPRODUCT_FULL=${PRODUCT_FULL}\nGIT_HASH=${REVISION}\n"

if [[ ${RHVER} -eq 7 ]]; then
    JOB_CMAKE='cmake3'
    CMAKE_OPTS+=" -DWITH_LIBEVENT=bundled"
fi

# ------------------------------------------------------------------------------
# Set compile options
# ------------------------------------------------------------------------------
if [[ "$COMPILER" != "default" ]]; then
    export CC=${COMPILER}
    export CXX=$(echo ${COMPILER} | sed -e 's/gcc/g++/; s/clang/clang++/')
fi

# CentOS 7
if [[ -f /opt/rh/devtoolset-8/enable ]]; then
    source /opt/rh/devtoolset-8/enable
fi

# ------------------------------------------------------------------------------
# Check mecab
# ------------------------------------------------------------------------------
# force to use mecab everywhere (except RHEL)
if [ -e /etc/redhat-release ]; then
    WITH_MECAB=""
else
    WITH_MECAB="system"
fi

if [[ "${MYSQL_VERSION}" == 8.0.* ]]; then
    CMAKE_OPTS+=" -DWITH_KEYRING_VAULT=ON -DWITH_KEYRING_VAULT_TEST=ON"
fi

# ------------------------------------------------------------------------------
# Set WITH_SSL
# ------------------------------------------------------------------------------
if [[ "${DOCKER_OS}" = "centos-7" ]]; then
  WITH_SSL="openssl11"
else
  WITH_SSL="system"
fi

# ------------------------------------------------------------------------------
# Get prebuilt V8 if we are building with JS Stored Programs support
# ------------------------------------------------------------------------------
if [[ ${WITH_JS_LANG} == 'ON' ]]; then
    V8_VERSION=$(grep 'SET(EXPECTED_V8_VERSION' ${SOURCEDIR}/cmake/v8.cmake | sed -re 's/.*"([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
    if [[ "${DOCKER_OS}" == "centos-8" ]] || [[ "${DOCKER_OS}" == "debian-bullseye" ]] || [[ "${DOCKER_OS}" == "ubuntu-focal" ]]; then
      # Platforms with older glibc need V8 built against older glibc as well.
      V8_ARCHIVE_NAME=v8_${V8_VERSION}-glibc2.31
    else
      V8_ARCHIVE_NAME=v8_${V8_VERSION}
    fi
    pushd ${DOWNLOAD_DIR}
        wget --progress=dot:giga https://downloads.percona.com/downloads/packaging/${V8_ARCHIVE_NAME}.tar.gz
        tar -xzf ${V8_ARCHIVE_NAME}.tar.gz
        rm -rf ${V8_ARCHIVE_NAME}.tar.gz
    popd
fi

# ------------------------------------------------------------------------------
# Finaly, compile!
# ------------------------------------------------------------------------------
pushd ${BUILD_DIR}
    ${JOB_CMAKE} \
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
        -DWITH_SSL=${WITH_SSL} \
        -DWITH_ROCKSDB=${WITH_ROCKSDB} \
        -DWITH_ROUTER=${WITH_ROUTER} \
        -DWITH_MYSQLX=${WITH_MYSQLX} \
        -DWITH_JS_LANG=${WITH_JS_LANG} \
        -DV8_INCLUDE_DIR=${DOWNLOAD_DIR}/v8/include \
        -DV8_LIB_DIR=${DOWNLOAD_DIR}/v8/out.gn/static/obj \
        -DWITH_MECAB=${WITH_MECAB} \
        -DENABLE_GCOV=${WITH_GCOV} \
        -DWITH_PACKAGE_FLAGS=OFF \
        -DWITH_SYSTEM_LIBS=ON \
        -DWITH_PROTOBUF=bundled \
        -DWITH_RAPIDJSON=bundled \
        -DWITH_ICU=bundled \
        -DBUILD_CONFIG=mysql_release \
        -DWITH_PAM=ON \
        -DWITH_NUMA=ON \
        -DWITH_ZLIB=bundled \
        -DWITH_ZSTD=bundled \
        -DWITH_LZ4=bundled \
        -DWITH_FIDO=bundled \
        -DWITH_INNODB_MEMCACHED=ON \
        -DDOWNLOAD_BOOST=ON \
        -DWITH_BOOST=${DOWNLOAD_DIR} \
        -DCMAKE_INSTALL_PREFIX=/usr/local/$PRODUCT_FULL \
        -DMYSQL_DATADIR=/usr/local/$PRODUCT_FULL/data \
        -DCOMPILATION_COMMENT="$COMMENT" \
        -DMYSQL_MAINTAINER_MODE=${MYSQL_MAINTAINER_MODE} \
        -DWITH_PERCONA_TELEMETRY=ON \
        ${TARGET_CFLAGS:+-DCMAKE_C_FLAGS="${TARGET_CFLAGS}" -DCMAKE_CXX_FLAGS="${TARGET_CFLAGS}"} \
        ${ANALYZER_OPTS} \
        ${CMAKE_OPTS} \
        ${SOURCEDIR} | tee ${WORKDIR}/cmake.log
    make ${MAKE_OPTS} | tee ${WORKDIR}/make_build.log
    make -j$(nproc) DESTDIR=${INSTALL_DIR} install | tee ${WORKDIR}/make_install.log
popd

# GCOV instrumentation files for coverage report.
if [[ ${WITH_GCOV} == 'ON' ]]; then
    pushd ${SOURCEDIR}
    wget https://raw.githubusercontent.com/Percona-QA/percona-qa/master/Coverage/dgcov.pl
    perl dgcov.pl --v --dump --source=$SOURCEDIR
    cp dumper.txt ${INSTALL_DIR}/usr/local/${PRODUCT_FULL}/
    popd
    pushd ${BUILD_DIR}
    find ./ -name "*.gcno" | cpio -pdm  ${INSTALL_DIR}/usr/local/${PRODUCT_FULL}/ || true
    popd
fi

tar -C ${INSTALL_DIR}/usr/local --owner=0 --group=0 -czf "${WORKDIR}/$PRODUCT_FULL.tar.gz" $PRODUCT_FULL
rm -rf ${INSTALL_DIR}

# Show final ccache statistics
if [[ "${USE_CCACHE}" == "yes" && -n $(command -v ccache) ]]; then
    echo "Final ccache statistics:"
    ccache -s
fi

if [[ "${KEEP_BUILD}" != "yes" ]]; then
    rm -rf ${BUILD_DIR}
fi

ls -l ${WORKDIR}
