#!/bin/bash

#  possible vars:
#      GIT_REPO
#      BRANCH
#      PERCONAFT_REPO
#      PERCONAFT_BRANCH
#      TOKUBACKUP_REPO
#      TOKUBACKUP_BRANCH
#      PURGE_TOKUDBBACKUP

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/..; pwd -P)/sources

if [ ! -d "${ROOT_DIR}" ]; then
    if [[ "${GIT_REPO}" =~ post-eol|private ]]; then
        GIT_REPO=$(echo ${GIT_REPO} | sed -e "s|github|${JNKPercona_token}@github|")
    fi
    git clone "${GIT_REPO:-https://github.com/percona/percona-server}" "${ROOT_DIR}"
fi

pushd $ROOT_DIR

    if [ -n "${GIT_REPO}" ]; then
        git remote set-url origin "${GIT_REPO}"
        git fetch --all
    fi

    git reset --hard
    git clean -xdf

    if [ -n "${BRANCH}" ]; then
        git checkout "${BRANCH}"
    fi
    if [ -n "${GIT_REPO}" -a -n "${BRANCH}" ]; then
        git pull origin ${BRANCH}
    fi

    if [ -n "${PERCONAFT_REPO}" ]; then
        git config -f .gitmodules submodule.PerconaFT.url "${PERCONAFT_REPO}"
    fi
    if [ -n "${PERCONAFT_BRANCH}" ]; then
        git config -f .gitmodules submodule.PerconaFT.branch "${PERCONAFT_BRANCH}"
    fi

    if [ -n "${TOKUBACKUP_REPO}" ]; then
        git config -f .gitmodules submodule.Percona-TokuBackup.url "${TOKUBACKUP_REPO}"
    fi
    if [ -n "${TOKUBACKUP_BRANCH}" ]; then
        git config -f .gitmodules submodule.Percona-TokuBackup.branch "${TOKUBACKUP_BRANCH}"
    fi
# update to the pinned revisions
    git submodule update --init

# update to the submodule HEAD (may be different from pinned)
    if [ -n "${PERCONAFT_REPO}" -o -n "${PERCONAFT_BRANCH}" ]; then
        git submodule update --init --remote storage/tokudb/PerconaFT
    fi

    if [ -n "${TOKUBACKUP_REPO}" -o -n "${TOKUBACKUP_BRANCH}" ]; then
        git submodule update --init --remote plugin/tokudb-backup-plugin/Percona-TokuBackup
    fi

    if [ "x${PURGE_TOKUDBBACKUP}" = "xtrue" ]; then
        rm -rf plugin/tokudb-backup-plugin/Percona-TokuBackup
        mkdir plugin/tokudb-backup-plugin/Percona-TokuBackup
    fi
popd
