#!/bin/bash

#  possible vars:
#      GIT_REPO
#      BRANCH

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/..; pwd -P)/sources

if [ ! -d "${ROOT_DIR}" ]; then
    git clone "${GIT_REPO:-https://github.com/percona/percona-server}" "${ROOT_DIR}"
fi

pushd $ROOT_DIR

    if [ -n "${GIT_REPO}" ]; then
        git remote set-url origin "${GIT_REPO}"
        git fetch --all --tags
    fi

    git reset --hard
    git clean -xdf

    if [ -n "${BRANCH}" ]; then
        git fetch --all --tags
        git checkout "${BRANCH}"

        # If BRANCH is actually a branch (not a tag or commit hash),
        # make sure it matches the remote exactly (force-push safe)
        if git rev-parse --abbrev-ref HEAD | grep -qv HEAD; then
            git reset --hard "origin/${BRANCH}" || true
        fi
    fi

    # update to the pinned revisions
    git submodule update --init
popd
