#!/bin/bash
#
# Execute this tool to test binary releases
#
#  possible jenkins vars:
#      CMAKE_BUILD_TYPE = (RelWithDebInfo Debug)
#      ANALYZER_OPTS = (-DWITH_ASAN=ON -DWITH_ASAN_SCOPE=ON -DWITH_MSAN=ON -DWITH_UBSAN=ON -DWITH_VALGRIND=ON)
#      MTR_ARGS
#      MTR_REPEAT = (1 ...)
#      MTR_SUITES = e.g "sys_vars,federated"
#      WORKER_NO = (1 ... 8)
#      DOCKER_OS = (ubuntu-jammy debian-bullseye oraclelinux-9 ...)
#      CI_FS_MTR = (yes no)
#      WITH_PS_PROTOCOL = (yes no)
#      KEYRING_VAULT_MTR = (yes no)
#      WITH_ROCKSDB = (ON OFF)
#      KEEP_BUILD = (yes no)
#      EXECUTE_SUITES_ONE_BY_ONE = (yes no)

set -o errexit
set -o xtrace

# Execution mode. If suites should be executed one by one, or all together
echo EXECUTE_SUITES_ONE_BY_ONE=$EXECUTE_SUITES_ONE_BY_ONE

function print_diagnostics() {
    local label="${1:-}"
    echo "=== Diagnostics${label:+: $label} ==="
    df -Th
    echo "------------------------------------------------"
    du -sh /dev/shm
    echo "------------------------------------------------"
    free -m
    echo "------------------------------------------------"
    cat /proc/meminfo
    echo "------------------------------------------------"
}

function execute() {
    local parallel=$1
    local extraOptions=$2
    local logFileSuffix=$3
    local worker="WORKER_${WORKER_NO}${logFileSuffix}"

    # ensure that there are not / in worker name (it can come from suites that have / in their names)
    worker=${worker//"/"/"_"}

    echo "Executing $extraOptions, logFileSuffix: $logFileSuffix"

    print_diagnostics "before MTR run ${worker}"

    start=`date +%s`

    if [[ "${HAVE_JUNIT}" == "1" ]]; then
        JUNIT_ARGS=" --junit-output=${RESULTS_DIR}/junit_${worker}.xml --junit-package=${DOCKER_OS}.${CMAKE_BUILD_TYPE}.${worker}"
    else
        JUNIT_ARGS=" --xml-report=${RESULTS_DIR}/junit_${worker}.xml"
    fi

    MTR_ARGS_NORMAL=${MTR_ARGS}

    MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
        --parallel=${parallel} \
        --result-file \
        --suite-timeout=${SUITE_TIMEOUT} \
        --testcase-timeout=${TESTCASE_TIMEOUT} \
        --force ${MYSQLD_ENV} \
        --max-test-fail=0 \
        ${MTR_ARGS_NORMAL} \
        ${extraOptions} \
        ${JUNIT_ARGS} || true

    ln -s $PWD/var $PWD/var_${worker}
    which rsync
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_${worker} ${RESULTS_DIR}/mtr_var

    pgrep -f mysqld | xargs -r kill -9 2>/dev/null || true

    rm -rf $PWD/var_${worker}

    df -Th
    du -sh /dev/shm

    end=`date +%s`
    runtime=$((end-start))
    echo KH,SUITES,${suites}-${logFileSuffix},time,$runtime
}

function executeSuites() {
  local suites="$1"
  local parallel="$2"
  local extraOptions="$3"
  local extraSuffix=${4:+-"$4"}

  if [[ -z ${suites} ]]; then
    return
  fi

  if [[ "${EXECUTE_SUITES_ONE_BY_ONE}" != "yes" ]]; then
    # Run all suites together
    execute "$parallel" "--suite=$suites $extraOptions" "$extraSuffix"
  else
    # Run suites one by one
    IFS=',' read -ra suiteList <<< "$suites"
    for suite in "${suiteList[@]}"; do
      echo "Executing suite: $suite"
      execute "$parallel" "--suite=$suite $extraOptions" ".${suite}${extraSuffix}"
    done
  fi
}

function split_suites() {
  local input="$1"
  suitesNormal=""
  suitesBig=""

  # Split input by comma
  IFS=',' read -ra suites <<< "$input"

  for suite in "${suites[@]}"; do
    case "$suite" in
      *"|nobig")
        suite_name="${suite%%|*}"
        suitesNormal+="${suitesNormal:+,}$suite_name"
        ;;
      *"|big")
        suite_name="${suite%%|*}"
        suitesBig+="${suitesBig:+,}$suite_name"
        ;;
      *)
        # No suffix → add to both
        suitesNormal+="${suitesNormal:+,}$suite"
        suitesBig+="${suitesBig:+,}$suite"
        ;;
    esac
  done
}

WORKDIR=$(cd ${1:-./build}; pwd -P)
BUILD_DIR=${WORKDIR}/build
RESULTS_DIR=${WORKDIR}/results
EXTRACT_DIR=${WORKDIR}/extract
mkdir -p ${RESULTS_DIR}

echo "*******************************************************"
echo "Starting tests on worker ${WORKER_NO}"
# --- static diagnostics (don't change during the run) ---
whoami
uname -a
nproc
lscpu || :
cat /sys/fs/cgroup/memory.max 2>/dev/null || cat /sys/fs/cgroup/memory/memory.limit_in_bytes 2>/dev/null || echo "cgroup memory limit: unknown"
prlimit
ulimit -a
mount
sudo dmesg -T 2>/dev/null | tail -20 || sudo dmesg 2>/dev/null | tail -20 || echo "dmesg not available"
# --- dynamic diagnostics (snapshot at startup) ---
print_diagnostics "startup"
echo "*******************************************************"

if [[ "${SERVER_VERSION}" == 8.0.* || "${SERVER_VERSION}" == 5.7.* ]]; then
    MTR_ARGS_KV_SUITE="--suite=keyring_vault"
else
    MTR_ARGS_KV_SUITE="--suite=component_keyring_vault"
fi
echo "SERVER_VERSION=$SERVER_VERSION"
echo "MTR_ARGS_KV_SUITE=$MTR_ARGS_KV_SUITE"

TESTCASE_TIMEOUT=30
SUITE_TIMEOUT=600
PARALLEL=$(grep -c ^processor /proc/cpuinfo)
# CentOS 7
if [[ -f /opt/rh/devtoolset-8/enable ]]; then
    source /opt/rh/devtoolset-8/enable
fi

JEMALLOC=$(find /lib* /usr/lib* /usr/local/lib* -type f -name 'libjemalloc.so*' | head -n1)
EATMYDATA=$(find /lib* /usr/lib* /usr/local/lib* -type f -name '*eatmyda*.so*' | head -n1)

#
if [[ -z "${EATMYDATA}" ]]; then
  echo "No libeatmydata.so lib found"
  exit 1
fi
#
# we test with system jemalloc
if [[ -z "${JEMALLOC}" ]]; then
  echo "No jemalloc lib found"
  exit 1
fi
#
MTR_ARGS+=" --timestamp --report-unstable-tests"
ANALYZER_MTR_ARGS=""
#
if [[ "${ANALYZER_OPTS}" == *WITH_VALGRIND=ON* ]]; then
  ANALYZER_MTR_ARGS+=" --valgrind --valgrind-clients --valgrind-option=--leak-check=full --valgrind-option=--show-leak-kinds=all"
  # Skip tests known to time out / be too slow under valgrind, if the list is present.
  # (mysql-test-run.pl errors out if --skip-test-list points to a missing file.)
  if [[ -f "${BUILD_DIR}/mysql-test/collections/valgrind-skip.list" ]]; then
    ANALYZER_MTR_ARGS+=" --skip-test-list=${BUILD_DIR}/mysql-test/collections/valgrind-skip.list"
  fi
  # defaults from mtr-test-run.pl; it will by multiplied later ($opt_testcase_timeout*= 10, $opt_suite_timeout*= 6)
  TESTCASE_TIMEOUT=15
  SUITE_TIMEOUT=300
  if [[ ${PARALLEL} -gt 1 ]]; then
    PARALLEL=$((PARALLEL/3))
  fi
fi

# hack for too big instances ;)
if [[ ${PARALLEL} -gt 10 ]]; then
  echo "Limit parallel ${PARALLEL} -> 10"
  PARALLEL=10
fi

if [[ "${ANALYZER_OPTS}" == *WITH_*SAN*=ON* ]]; then
    ANALYZER_MTR_ARGS+=" --sanitize"
    ANALYZER_MTR_ARGS+=" --mysqld=--thread_stack=2M"
fi

MTR_ARGS+=${ANALYZER_MTR_ARGS}

if [[ -n "${MTR_REPEAT}" ]]; then
  MTR_ARGS+=" --repeat=${MTR_REPEAT}"
fi

if [[ "${MTR_ARGS}" == *"--suite=max_parts"* ]]; then
    TESTCASE_TIMEOUT=$((TESTCASE_TIMEOUT * 3))
fi

#
# force to use mecab everywhere (except RHEL)
if [[ ! -e /etc/redhat-release ]]; then
    MTR_ARGS+=" --mysqld=--loose-mecab-rc-file=/etc/mecabrc"
fi
#

if [[ $MTR_ARGS == *"--big-test"* ]] || [[ $MTR_ARGS == *"--only-big-test"* ]]; then
    TESTCASE_TIMEOUT=$((TESTCASE_TIMEOUT * 2))
    SUITE_TIMEOUT=$((SUITE_TIMEOUT * 2))
fi

#
# execute big tests in separate run
BIG_TEST=0
ONLY_BIG_TEST=0
if [[ $MTR_ARGS == *"--big-test"* ]]; then
    BIG_TEST=1
fi
if [[ $MTR_ARGS == *"--only-big-test"* ]]; then
    ONLY_BIG_TEST=1
    BIG_TEST=1
fi
MTR_ARGS=${MTR_ARGS//"--only-big-test"/""}
MTR_ARGS=${MTR_ARGS//"--big-test"/""}

#
# unit tests
UNIT_TESTS=0
if [[ $MTR_ARGS == *"--unit-tests-report"* ]]; then
    if [ -e ${BUILD_DIR}/mysql-test/mysql-test-run.pl ]; then
        UNIT_TESTS=1
    else
        echo "Skipping unit tests. Couldn't find ${BUILD_DIR}/mysql-test/mysql-test-run.pl"
    fi
fi
MTR_ARGS=${MTR_ARGS//"--unit-tests-report"/""}

#
# >>>> execute all unit tests at the beginning with main.1st only using an original build (not files for ".tar.gz" archive)
if [[ $UNIT_TESTS == "1" ]]; then
    # /tmp/sources is required by an original build in $BUILD_DIR to run unit tests
    tests="main.1st"
    suiteNoSlash="UNIT_TESTS"
    echo "Executing unit tests with $tests"

    print_diagnostics "before unit tests"
    start=`date +%s`

    if [[ "${KEYRING_VAULT_MTR}" == 'yes' ]]; then
        MTR_VAULT_ARRAY=(
            MTR_VAULT_ADDRESS=${VAULT_V2_DEV_ADDRESS}
            MTR_VAULT_ADMIN_TOKEN=${VAULT_V2_DEV_ROOT_TOKEN}
            MTR_VAULT_PLUGIN_TOKEN=${VAULT_V2_DEV_MTR_TOKEN}
            MTR_VAULT_VERSION=2
        )
    fi

    ls -l /tmp/sources/mysql-test || :
    grep -q "opt_junit_package" /tmp/sources/mysql-test/mysql-test-run.pl && HAVE_JUNIT=1 || HAVE_JUNIT=0
    if [[ "${HAVE_JUNIT}" == "1" ]]; then
        JUNIT_UNIT_TESTS_ARGS=" --junit-output=${RESULTS_DIR}/junit_${suiteNoSlash}.xml --junit-package=${DOCKER_OS}.${CMAKE_BUILD_TYPE}.WORKER_${WORKER_NO}.${suiteNoSlash}"
    else
        JUNIT_UNIT_TESTS_ARGS=" --xml-report=${RESULTS_DIR}/junit_${suiteNoSlash}.xml"
    fi

    pushd ${BUILD_DIR}/mysql-test
    env "${MTR_VAULT_ARRAY[@]}" MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
        --parallel=${PARALLEL} \
        --result-file \
        --unit-tests-report \
        ${tests} \
        ${MTR_ARGS} \
        --force \
        --max-test-fail=0 \
        ${JUNIT_UNIT_TESTS_ARGS} || true

    ln -s ${BUILD_DIR}/mysql-test/var $PWD/var_${suiteNoSlash}
    which rsync
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_${suiteNoSlash} ${RESULTS_DIR}/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_${suiteNoSlash}
    popd

    df -Th
    du -sh /dev/shm

    end=`date +%s`
    runtime=$((end-start))
    echo KH,UNIT_TESTS,${tests},time,$runtime
fi


if [[ "${KEEP_BUILD}" != "yes" ]]; then
    echo "*******************************************************"
    echo "Remove the original build"
    ls -l ${BUILD_DIR} || :
    du -sh ${BUILD_DIR} 2>/dev/null || echo "Build dir does not exist"
    sudo rm -rf ${BUILD_DIR}
    echo "After build removal:"
    free -m
    df -Th
fi

echo "*******************************************************"
echo "Decompress \".tar.gz\" archive and use it for MTR tests"
free -m
df -Th
ls -lh ${WORKDIR}/*.tar.gz
rm -rf ${EXTRACT_DIR}
mkdir -p ${EXTRACT_DIR}
tar -C ${EXTRACT_DIR} --strip-components=1 -zxpf $(ls ${WORKDIR}/*.tar.gz | head -1)
echo "Extraction complete"
free -m
df -Th
du -sh ${EXTRACT_DIR}
cd ${EXTRACT_DIR}/mysql-test


if [[ "${ANALYZER_OPTS}" == *WITH_ASAN=ON* ]]; then
  export ASAN_OPTIONS=allocator_may_return_null=true
  # trying to find the proper library
  MYSQLD=$(find ${EXTRACT_DIR}/bin -name mysqld)
  LIBASAN=$(ldd ${MYSQLD} | grep libasan | awk '{print $3}')
  ADD_TO_LD_PRELOAD="${LIBASAN}:"
fi

#
# adjustments for Valgrind
if [[ "${ANALYZER_OPTS}" == *WITH_VALGRIND=ON* ]]; then
    MYSQLD_ENV=--mysqld-env=\"LD_PRELOAD=${ADD_TO_LD_PRELOAD:-}${EATMYDATA}\"
else
    MYSQLD_ENV=--mysqld-env=\"LD_PRELOAD=${ADD_TO_LD_PRELOAD:-}${JEMALLOC}:${EATMYDATA}\"
fi


#
# Running MTR test cases
MTR_ARGS="${MTR_ARGS} --no-unit-tests"


# >>>> main MTR execution loop starts here
# Check if --junit-package option is avail from mysql-test-run.pl
grep -q "opt_junit_package" ${EXTRACT_DIR}/mysql-test/mysql-test-run.pl && HAVE_JUNIT=1 || HAVE_JUNIT=0

split_suites "$MTR_SUITES"

echo "MTR normal suites: $suitesNormal"
echo "MTR big suites: $suitesBig"

if [[ "$ONLY_BIG_TEST" == "1" ]]; then
  executeSuites "$suitesBig"    "${PARALLEL}" "--only-big-test" "big"
elif [[ "$BIG_TEST" == "1" ]]; then
  executeSuites "$suitesNormal" "${PARALLEL}" "" ""
  executeSuites "$suitesBig"    "${PARALLEL}" "--only-big-test" "big"
else
  # executeSuites $suites $parallel $extraOptions $logFileSuffix
  executeSuites "$suitesNormal" "${PARALLEL}" "" ""
fi
# <<<< main MTR execution loop ends here


#
# CI FS tests
if [[ "${CI_FS_MTR}" == 'yes' ]]; then
    echo "Running CI FS tests"
    start=`date +%s`

    MTR_ARGS_CI=${MTR_ARGS}

    # no --mem allowed if vardir specified
    MTR_ARGS_CI=${MTR_ARGS_CI//"--mem"/""}

    if [[ $BIG_TEST == "1" ]]; then
        MTR_ARGS_CI+=" --big-test"
    fi

    # Collect all CI_FS tests
    CI_TESTS=$(grep --exclude="*.inc" --exclude="*.log" -rl . -e include/have_case_insensitive_file_system.inc | awk -F '/' '{print $(NF-2)"."$NF}' | sed 's/\.test//g' | sed 's/^\./main/g')
    # Requested in PS-7602
    if [[ "${SERVER_VERSION}" != 5.7.* && ${CMAKE_BUILD_TYPE} == Debug ]]; then
        CI_TESTS+=" information_schema.i_s_schema_definition_debug"
    fi

    # Filter out disabled tests
    # Skip lines starting with #
    # Grab until whitespace or :
    DISABLED_TESTS=$(grep -P -o '^\s*[^#][^:\s]*' collections/disabled.def || true)

    set +x
    for CURRENT_TEST in $DISABLED_TESTS; do
        CI_TESTS=${CI_TESTS//"$CURRENT_TEST"/""}
    done
    set -x

    if [[ "${HAVE_JUNIT}" == "1" ]]; then
        JUNIT_CI_FS_ARGS=" --junit-output=${RESULTS_DIR}/junit_ci_fs.xml --junit-package=${DOCKER_OS}.${CMAKE_BUILD_TYPE}.WORKER_${WORKER_NO}.ci_fs"
    else
        JUNIT_CI_FS_ARGS=" --xml-report=${RESULTS_DIR}/junit_ci_fs.xml"
    fi

    MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
        --result-file \
        --force ${MYSQLD_ENV} \
        --max-test-fail=0 \
        --suite-timeout=${SUITE_TIMEOUT} \
        --parallel=$PARALLEL \
        --testcase-timeout=${TESTCASE_TIMEOUT} \
        ${MTR_ARGS_CI} \
        --tmpdir="/tmp/ps_mtr_tempdir" \
        --vardir="/tmp/ci_disk_dir/var" \
        ${CI_TESTS} \
        ${ANALYZER_MTR_ARGS} \
        ${JUNIT_CI_FS_ARGS} || true

    ln -s /tmp/ci_disk_dir/var $PWD/var_ci_fs
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_ci_fs ${RESULTS_DIR}/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_ci_fs

    end=`date +%s`
    runtime=$((end-start))
    echo KH,SUITE_TOTAL,CI_FS_tests,time,$runtime
fi

#
# PS PROTOCOL tests
if [[ "${SERVER_VERSION}" != 5.7.* && "${WITH_PS_PROTOCOL}" == 'yes' ]]; then
    echo "Running PS PROTOCOL tests"
    start=`date +%s`

    MTR_ARGS_PS=${MTR_ARGS}

    if [[ $BIG_TEST == "1" ]]; then
        MTR_ARGS_PS+=" --big-test"
    fi

    # Collect all PS_PROTOCOL tests
    PS_TESTS=$(grep --exclude="*.inc" --exclude="*.log" -rl . -e include/have_ps_protocol.inc | awk -F '/' '{print $(NF-2)"."$NF}' | sed 's/\.test//g' | sed 's/^\./main/g')

    # Filter out disabled tests
    # Skip lines starting with #
    # Grab until whitespace or :
    DISABLED_TESTS=$(grep -P -o '^\s*[^#][^:\s]*' collections/disabled.def || true)

    set +x
    for CURRENT_TEST in $DISABLED_TESTS; do
        PS_TESTS=${PS_TESTS//"$CURRENT_TEST"/""}
    done
    set -x

    if [[ "${HAVE_JUNIT}" == "1" ]]; then
        JUNIT_PS_PROTOCOL_ARGS=" --junit-output=${RESULTS_DIR}/junit_ps_protocol.xml --junit-package=${DOCKER_OS}.${CMAKE_BUILD_TYPE}.WORKER_${WORKER_NO}.ps_protocol"
    else
        JUNIT_PS_PROTOCOL_ARGS=" --xml-report=${RESULTS_DIR}/junit_ps_protocol.xml"
    fi

    MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
        --result-file \
        --force ${MYSQLD_ENV} \
        --max-test-fail=0 \
        --suite-timeout=${SUITE_TIMEOUT} \
        --parallel=$PARALLEL \
        --ps-protocol \
        --testcase-timeout=${TESTCASE_TIMEOUT} \
        ${MTR_ARGS_PS} \
        ${PS_TESTS} \
        ${ANALYZER_MTR_ARGS} \
        ${JUNIT_PS_PROTOCOL_ARGS} || true

    ln -s $PWD/var $PWD/var_ps_protocol
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_ps_protocol ${RESULTS_DIR}/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_ps_protocol

    end=`date +%s`
    runtime=$((end-start))
    echo KH,SUITE_TOTAL,PS_protocol_tests,time,$runtime
fi


if [[ ${KEYRING_VAULT_MTR} == 'yes' ]]; then
    echo "Running KEYRING_VAULT tests"
    start=`date +%s`

    MTR_ARGS_KV=${MTR_ARGS}

    if [[ $BIG_TEST == "1" ]]; then
        MTR_ARGS_KV+=" --big-test"
    fi

    if [ -f /usr/bin/yum ]; then
        if [[ -f /opt/rh/httpd24/enable ]]; then
            source /opt/rh/httpd24/enable
        fi
    fi

    echo "Running tests with Hashicorp Vault in Dev mode"
    if [[ "${HAVE_JUNIT}" == "1" ]]; then
        JUNIT_VAULT_V1_DEV_TC_ARGS=" --junit-output=${RESULTS_DIR}/junit_keyring_vault_dev_v1.xml --junit-package=${DOCKER_OS}.${CMAKE_BUILD_TYPE}.WORKER_${WORKER_NO}.keyring_vault_dev_v1"
    else
        JUNIT_VAULT_V1_DEV_TC_ARGS=" --xml-report=${RESULTS_DIR}/junit_keyring_vault_dev_v1.xml"
    fi

    MTR_VAULT_ADDRESS=${VAULT_V1_DEV_ADDRESS} \
    MTR_VAULT_ADMIN_TOKEN=${VAULT_V1_DEV_ROOT_TOKEN} \
    MTR_VAULT_PLUGIN_TOKEN=${VAULT_V1_DEV_MTR_TOKEN} \
    MTR_VAULT_VERSION=1 \
    MTR_BUILD_THREAD=auto ./mtr \
        --force \
        --max-test-fail=0 \
        --parallel=$PARALLEL \
        --retry=0 \
        ${MTR_ARGS_KV} \
        ${MTR_ARGS_KV_SUITE} \
        ${ANALYZER_MTR_ARGS} \
        ${JUNIT_VAULT_V1_DEV_TC_ARGS} || true

    ln -s $PWD/var $PWD/var_kv1_dev
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_kv1_dev ${RESULTS_DIR}/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_kv1_dev

    if [[ "${HAVE_JUNIT}" == "1" ]]; then
        JUNIT_VAULT_V2_DEV_TC_ARGS=" --junit-output=${RESULTS_DIR}/junit_keyring_vault_dev_v2.xml --junit-package=${DOCKER_OS}.${CMAKE_BUILD_TYPE}.WORKER_${WORKER_NO}.keyring_vault_dev_v2"
    else
        JUNIT_VAULT_V2_DEV_TC_ARGS=" --xml-report=${RESULTS_DIR}/junit_keyring_vault_dev_v2.xml"
    fi

    MTR_VAULT_ADDRESS=${VAULT_V2_DEV_ADDRESS} \
    MTR_VAULT_ADMIN_TOKEN=${VAULT_V2_DEV_ROOT_TOKEN} \
    MTR_VAULT_PLUGIN_TOKEN=${VAULT_V2_DEV_MTR_TOKEN} \
    MTR_VAULT_VERSION=2 \
    MTR_BUILD_THREAD=auto ./mtr \
        --force \
        --max-test-fail=0 \
        --parallel=$PARALLEL \
        --retry=0 \
        ${MTR_ARGS_KV} \
        ${MTR_ARGS_KV_SUITE} \
        ${ANALYZER_MTR_ARGS} \
        ${JUNIT_VAULT_V2_DEV_TC_ARGS} || true

    ln -s $PWD/var $PWD/var_kv2_dev
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_kv2_dev ${RESULTS_DIR}/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_kv2_dev

    echo "Running tests with Hashicorp Vault in Production mode"
    if [[ "${HAVE_JUNIT}" == "1" ]]; then
        JUNIT_VAULT_V1_PROD_TC_ARGS=" --junit-output=${RESULTS_DIR}/junit_keyring_vault_prod_v1.xml --junit-package=${DOCKER_OS}.${CMAKE_BUILD_TYPE}.WORKER_${WORKER_NO}.keyring_vault_prod_v1"
    else
        JUNIT_VAULT_V1_PROD_TC_ARGS=" --xml-report=${RESULTS_DIR}/junit_keyring_vault_prod_v1.xml"
    fi

    MTR_VAULT_ADDRESS=${VAULT_V1_PROD_ADDRESS} \
    MTR_VAULT_ADMIN_TOKEN=${VAULT_V1_PROD_ROOT_TOKEN} \
    MTR_VAULT_PLUGIN_TOKEN=${VAULT_V1_PROD_MTR_TOKEN} \
    MTR_VAULT_CA="${WORKDIR}/cert/vault-prod-v1-ca.pem" \
    MTR_VAULT_VERSION=1 \
    MTR_BUILD_THREAD=auto ./mtr \
        --force \
        --max-test-fail=0 \
        --parallel=$PARALLEL \
        --retry=0 \
        ${MTR_ARGS_KV} \
        ${MTR_ARGS_KV_SUITE} \
        ${ANALYZER_MTR_ARGS} \
        ${JUNIT_VAULT_V1_PROD_TC_ARGS} || true

    ln -s $PWD/var $PWD/var_kv1_prod
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_kv1_prod ${RESULTS_DIR}/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_kv1_prod

    if [[ "${HAVE_JUNIT}" == "1" ]]; then
        JUNIT_VAULT_V2_PROD_TC_ARGS=" --junit-output=${RESULTS_DIR}/junit_keyring_vault_prod_v2.xml --junit-package=${DOCKER_OS}.${CMAKE_BUILD_TYPE}.WORKER_${WORKER_NO}.keyring_vault_prod_v2"
    else
        JUNIT_VAULT_V2_PROD_TC_ARGS=" --xml-report=${RESULTS_DIR}/junit_keyring_vault_prod_v2.xml"
    fi

    MTR_VAULT_ADDRESS=${VAULT_V2_PROD_ADDRESS} \
    MTR_VAULT_ADMIN_TOKEN=${VAULT_V2_PROD_ROOT_TOKEN} \
    MTR_VAULT_PLUGIN_TOKEN=${VAULT_V2_PROD_MTR_TOKEN} \
    MTR_VAULT_CA="${WORKDIR}/cert/vault-prod-v2-ca.pem" \
    MTR_VAULT_VERSION=2 \
    MTR_BUILD_THREAD=auto ./mtr \
        --force \
        --max-test-fail=0 \
        --parallel=$PARALLEL \
        --retry=0 \
        ${MTR_ARGS_KV} \
        ${MTR_ARGS_KV_SUITE} \
        ${ANALYZER_MTR_ARGS} \
        ${JUNIT_VAULT_V2_PROD_TC_ARGS} || true

    ln -s $PWD/var $PWD/var_kv2_prod
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_kv2_prod ${RESULTS_DIR}/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_kv2_prod

    end=`date +%s`
    runtime=$((end-start))
    echo KH,SUITE_TOTAL,KEYRING_VAULT_tests,time,$runtime
fi

rm -fr ${EXTRACT_DIR}/mysql-test/var
if [[ "${KEEP_BUILD}" != "yes" ]]; then
    rm -rf ${EXTRACT_DIR}
fi

cd ${WORKDIR}
tar -C ${RESULTS_DIR} --owner=0 --group=0 -czf "${RESULTS_DIR}/ps80-test-mtr_logs-${WORKER_NO}.tar.gz" mtr_var

ls -l ${WORKDIR}
ls -l ${RESULTS_DIR}
