#!/bin/bash
#
set -o xtrace
set -o errexit
#
DOWNLOAD_ROOT=/tmp/source_downloads
wget_loop() {
    local FILE="$1"
    local URL="$2"

    mkdir -p "${DOWNLOAD_ROOT}"
    until wget --progress=dot:giga -O "${DOWNLOAD_ROOT}/${FILE}" "${URL}"; do
        echo "sleep before retry"
        sleep 1
    done
}
#
if [ -f /usr/bin/yum ]; then
  RHVER="$(rpm --eval %rhel)"
  rpm --eval %_arch > /etc/yum/vars/basearch

  if [[ ${RHVER} -eq 6 ]]; then
    curl https://jenkins.percona.com/downloads/cent6/centos6-eol.repo --output /etc/yum.repos.d/CentOS-Base.repo
  fi

  until yum -y update; do
    yum clean all
    echo "waiting"
    sleep 1
  done

  PKGLIST+=" wget"

  until yum -y install epel-release; do
    echo "waiting"
    sleep 1
  done
  if [[ ${RHVER} -eq 6 ]]; then
    rm /etc/yum.repos.d/epel-testing.repo
    curl https://jenkins.percona.com/downloads/cent6/centos6-epel-eol.repo --output /etc/yum.repos.d/epel.repo
  fi

  if [[ ${RHVER} -eq 8 ]]; then
      PKGLIST+=" dnf-utils"
      until yum -y install ${PKGLIST} ; do
        echo "waiting"
        sleep 1
      done

      dnf config-manager --set-enabled powertools epel-playground
      PKGLIST+=" libedit-devel"
  fi

  if [[ ${RHVER} -lt 8 ]] && [[ "$(rpm --eval %{_arch})" == "x86_64" ]]; then
    until yum -y install centos-release-scl; do
      echo "waiting"
      sleep 1
    done
    if [[ ${RHVER} -eq 6 ]]; then
      curl https://jenkins.percona.com/downloads/cent6/centos6-scl-eol.repo --output /etc/yum.repos.d/CentOS-SCLo-scl.repo
      curl https://jenkins.percona.com/downloads/cent6/centos6-scl-rh-eol.repo --output /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo
    fi
  fi
  until yum -y install ${PKGLIST}; do
    echo "waiting"
    sleep 1
  done

  if [[ ${RHVER} -eq 8 ]]; then
      wget -O /etc/yum.repos.d/percona-dev.repo https://jenkins.percona.com/yum-repo/percona-dev.repo
      dnf config-manager --set-enabled powertools epel-playground
  fi

  PKGLIST=" \
    gcc-c++ gperf ncurses-devel perl readline-devel openssl-devel jemalloc zip unzip \
    time zlib-devel libaio-devel bison cmake pam-devel jemalloc-devel valgrind re2-devel \
    perl-Time-HiRes openldap-devel perl-Env perl-Data-Dumper libicu-devel perl-Sys-MemInfo \
    perl-JSON MySQL-python perl-Digest perl-Digest-MD5 \
    numactl-devel git which make rpm-build ccache libtool redhat-lsb-core sudo libasan lz4-devel \
    libzstd-devel tzdata zstd mysql-devel perl-DBI perl-DBD-mysql jq openssl perl-XML-Simple libcurl-devel perl-Test-Simple \
    "

    if [[ ${RHVER} -eq 8 ]]; then
        PKGLIST+=" lz4 perl-Memoize perl-open valgrind-devel libubsan rpcgen libtirpc-devel golang libunwind-devel python2 python3 libatomic"
        PKGLIST_DEVTOOLSET10+=" gcc-toolset-10-gcc-c++ gcc-toolset-10-binutils"
        PKGLIST_DEVTOOLSET10+=" gcc-toolset-10-valgrind gcc-toolset-10-valgrind-devel gcc-toolset-10-libatomic-devel"
        PKGLIST_DEVTOOLSET10+=" gcc-toolset-10-libasan-devel gcc-toolset-10-libubsan-devel"
    fi

    if [[ ${RHVER} -eq 7 ]]; then
        PKGLIST+=" go-toolset-7 libunwind-devel httpd24-curl"
        PKGLIST_DEVTOOLSET10+=" devtoolset-10-gcc-c++ devtoolset-10-binutils"
        PKGLIST_DEVTOOLSET10+=" devtoolset-10-valgrind devtoolset-10-valgrind-devel devtoolset-10-libatomic-devel"
        PKGLIST_DEVTOOLSET10+=" devtoolset-10-libasan-devel devtoolset-10-libubsan-devel"
    fi

    if [[ ${RHVER} != 6 ]]; then
        PKGLIST+=" python3-pip python3-devel"
    fi

# Percona-Server
    if [[ ${RHVER} -eq 6 ]]; then
        wget -O /etc/yum.repos.d/slc6-devtoolset.repo http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo
        wget -O /etc/pki/rpm-gpg/RPM-GPG-KEY-cern https://raw.githubusercontent.com/cms-sw/cms-docker/master/slc6/RPM-GPG-KEY-cern
        PKGLIST+=" devtoolset-2-gcc-c++ devtoolset-2-binutils"
        PKGLIST+=" devtoolset-2-libasan-devel"
        PKGLIST+=" devtoolset-2-valgrind devtoolset-2-valgrind-devel"
        PKGLIST+=" libevent2-devel python-argparse"
    fi

    if [[ ${RHVER} -gt 6 ]]; then
        PKGLIST+=" libevent-devel"
    fi

#   Percona-Server 8.0
    if [[ ${RHVER} -lt 8 ]]; then
        PKGLIST+=" devtoolset-7-gcc-c++ devtoolset-7-binutils cmake3"
        PKGLIST+=" devtoolset-7-libasan-devel devtoolset-7-libubsan-devel boost-devel"
        PKGLIST+=" devtoolset-7-valgrind devtoolset-7-valgrind-devel devtoolset-7-libatomic-devel"
        PKGLIST+=" devtoolset-8-gcc-c++ devtoolset-8-binutils"
        PKGLIST+=" devtoolset-8-libasan-devel devtoolset-8-libubsan-devel"
        PKGLIST+=" devtoolset-8-valgrind devtoolset-8-valgrind-devel devtoolset-8-libatomic-devel perl-Digest-Perl-MD5 libedit-devel"
    fi

    until yum -y install ${PKGLIST} ; do
        echo "waiting"
        sleep 1
    done

    if [[ ${RHVER} -eq 7 ]]; then
        until yum -y --enablerepo=centos-sclo-rh-testing install ${PKGLIST_DEVTOOLSET10}; do
            echo "waiting"
            sleep 1
        done
    elif [[ ${RHVER} -eq 8 ]]; then
        yum -y install centos-release-stream
        until yum -y install ${PKGLIST_DEVTOOLSET10}; do
            echo "waiting"
            sleep 1
        done
        yum -y remove centos-release-stream
    fi

    if [[ ${RHVER} -eq 8 ]]; then
        ln -fs /usr/bin/python3 /usr/bin/python
    fi

    if [[ ${RHVER} != 6 ]]; then
        # Install mysqlclient by pip as there's no candidate in repositories
        if [[ ${RHVER} -eq 7 ]]; then
            source /opt/rh/devtoolset-7/enable
        fi
        pip3 install mysqlclient
    fi

#   this is workaround for https://bugs.mysql.com/bug.php?id=95222 as soon as the issue is fixed we need to remove it 
    if [ -f '/anaconda-post.log' ]; then
        rm /anaconda-post.log
    fi
fi

if [ -f /usr/bin/apt-get ]; then
    echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

    until apt-get update; do
        sleep 1
        echo "waiting"
    done

    until apt-get -y install lsb-release gnupg wget bc; do
        sleep 1
        echo "waiting"
    done

    DIST=$(lsb_release -sc)
    if [[ ${DIST} != 'focal' ]] && [[ ${DIST} != 'hirsute' ]]; then
        echo "deb http://jenkins.percona.com/apt-repo/ ${DIST} main" > /etc/apt/sources.list.d/percona-dev.list
        wget -q -O - http://jenkins.percona.com/apt-repo/8507EFA5.pub | apt-key add -
        wget -q -O - http://jenkins.percona.com/apt-repo/CD2EFD2A.pub | apt-key add -
    fi

    until apt-get update; do
        sleep 1
        echo "waiting"
    done

    PKGLIST=" \
        curl bison cmake perl libssl-dev gcc g++ libaio-dev libldap2-dev libwrap0-dev gdb zip unzip gawk \
        libmecab-dev libncurses5-dev libreadline-dev libpam-dev zlib1g-dev libcurl4-openssl-dev \
        libnuma-dev libjemalloc-dev libc6-dbg valgrind libjson-perl libevent-dev pkg-config \
        libmecab2 mecab mecab-ipadic git autoconf libgsasl7 libsasl2-dev libsasl2-modules devscripts \
        debconf debhelper fakeroot po-debconf psmisc ccache libtool sudo liblz4-dev liblz4-tool libedit-dev libssl-dev \
        tzdata golang libunwind-dev zstd python3-mysqldb libdbi-perl libdbd-mysql-perl \
        jq openssl libxml-simple-perl \
    "

    DISTRIBUTOR_ID=$(lsb_release -i -s)
    RELEASE=$(lsb_release -r -s)
    if [[ ${DISTRIBUTOR_ID} == Ubuntu ]] && [[ $(echo "${RELEASE} >= 18.0" | bc -l) == 1 ]]; then
        PKGLIST+=" libasan5"
    fi

    if [[ ${RELEASE} > "16.0" ]]; then
        PKGLIST+=" libre2-dev"
    fi

    # On Ubuntu install zstd/libsys-meminfo-perl only for Xenial (16.X) and higher
    if [[ ${DISTRIBUTOR_ID} == Ubuntu ]] && [[ $(echo "${RELEASE} >= 16.0" | bc -l) == 1 ]]; then
        PKGLIST+=" libsys-meminfo-perl"

        if [[ $(echo "${RELEASE} >= 18.0" | bc -l) == 1 ]]; then
            # libzstd-dev for Bionic and higher
            PKGLIST+=" libzstd-dev libboost-dev libatomic1"
        else
            # libzstd1-dev for Xenial
            PKGLIST+=" libzstd1-dev"
        fi
    fi

    # On Debian install zstd/perl-Sys-MemInfo only for Stretch (9.X) and higher
    if [[ ${DISTRIBUTOR_ID} == Debian ]] && [[ $(echo "${RELEASE} >= 9.0" | bc -l) == 1 ]]; then
        PKGLIST+=" libzstd-dev libsys-meminfo-perl"
    fi

    # For Debian buster install libre2-dev
    if [[ ${DISTRIBUTOR_ID} == Debian ]] && [[ $(echo "${RELEASE} >= 10" | bc -l) == 1 ]]; then
        PKGLIST+=" libre2-dev"
    fi

    if [[ ${DIST} == "hirsute" ]]; then
        PKGLIST+=" libzbd-dev clang-12 pkg-config make libgflags-dev nvme-cli util-linux fio zbd-utils"
    fi

    until apt-get -y install ${PKGLIST}; do
        echo "waiting"
        sleep 1
    done

    apt-get -y clean

    if [[ -L /usr/bin/python ]]; then
        rm /usr/bin/python
    fi
    ln -fs /usr/bin/python3 /usr/bin/python
fi

if [ ! -f /usr/local/lib/libeatmydata.so ]; then
    git clone https://github.com/stewartsmith/libeatmydata /tmp/libeatmydata
    pushd /tmp/libeatmydata
        # PS-7639: Needed for CentOS 6 because of ancient autoconf
        if [ -f /usr/bin/yum ]; then
            RHVER="$(rpm --eval %rhel)"
            if [[ ${RHVER} -eq 6 ]]; then
                git checkout df7ddeb0345104f25b5b7bb154bc6a008c8c8404
            fi
        fi
        autoreconf --force --install
        ./configure
        make
        make install
    popd
    rm -rf /tmp/libeatmydata
fi

# PS-7159 remove localhost from ipv6 
# sed -re "s/^(::1.*)\slocalhost\b(.*)$/\1 \2/g" /etc/hosts 1<> /etc/hosts

# NB: resulting docker image will be used for building all branches: 5.6, 5.7, 8.0
# boost 1.59.0 needed for percona-server 5.7
wget_loop 'boost_1_59_0.tar.gz' 'http://downloads.sourceforge.net/boost/boost/1.59.0/boost_1_59_0.tar.gz'

# boost 1.67.0 needed for percona-server 8.0
wget_loop 'boost_1_67_0.tar.gz' 'http://downloads.sourceforge.net/boost/boost/1.67.0/boost_1_67_0.tar.gz'

# googletest 1.8.0 needed for percona-server versions 5.6 to 8.0
wget_loop 'googletest-release-1.8.0.zip' 'https://github.com/google/googletest/archive/release-1.8.0.zip'
