#!/bin/bash

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/../sources; pwd -P)
SCRIPTS_DIR=$(cd $(dirname $0)/../local; pwd -P)
SOURCE_IMAGE=${1:-centos:7}

docker run --rm \
    --cap-add SYS_PTRACE \
    --mount type=bind,source=${ROOT_DIR},destination=/tmp/ps \
    --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
    illiapshonkin/ps-7749:${SOURCE_IMAGE//[:\/]/-} \
    sh -c "
    set -o errexit
    set -o xtrace

    export JOB_CMAKE='${JOB_CMAKE}'
    export COMPILER='${COMPILER}'
    export CMAKE_BUILD_TYPE='${CMAKE_BUILD_TYPE}'
    export ANALYZER_OPTS='${ANALYZER_OPTS}'
    export WITH_TOKUDB='${WITH_TOKUDB}'
    export WITH_ROCKSDB='${WITH_ROCKSDB}'
    export WITH_ROUTER='${WITH_ROUTER}'
    export WITH_MYSQLX='${WITH_MYSQLX}'
    export WITH_BORINGSSL='${WITH_BORINGSSL}'
    export WITH_KEYRING_VAULT='${WITH_KEYRING_VAULT}'
    export CMAKE_OPTS='${CMAKE_OPTS}'
    export MAKE_OPTS='${MAKE_OPTS}'
    export BUILD_COMMENT='${BUILD_COMMENT}'
    export TAG='${TAG}'
    export DIST_NAME='${DIST_NAME}'
    export SSL_VER='${SSL_VER}'
    export ZEN_FS_MTR='${ZEN_FS_MTR}'
    export DOCKER_OS='${DOCKER_OS//:/-}'

    mkdir  /tmp/results
    cp -r /tmp/source_downloads /tmp/results/source_downloads
    sudo chown mysql:mysql /tmp/ps/mysql-test/collections /tmp/ps/storage/rocksdb/rocksdb/util /tmp/ps/rocksdb/util || :
    bash -x /tmp/scripts/build-binary /tmp/results /tmp/ps

    sudo rm -rf /tmp/ps/results
    sudo mkdir /tmp/ps/results
    sudo mv /tmp/results/*.tar.gz /tmp/ps/results/
    sudo chown -R $(id -u):$(id -g) /tmp/ps/results /tmp/ps/mysql-test/collections /tmp/ps/storage/rocksdb/rocksdb/util /tmp/ps/rocksdb/util
"
