#!/bin/bash

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/..; pwd -P)
SCRIPTS_DIR=$ROOT_DIR/local
SOURCES_DIR=$ROOT_DIR/sources
DOCKER_OS=${1:-centos:7}
SOURCE_IMAGE=${DOCKER_OS//[:\/]/-}
WORKER_NO=${2:-0}
BUILD_DIR=$ROOT_DIR/${SOURCE_IMAGE}_${CMAKE_BUILD_TYPE}
mkdir -p $BUILD_DIR

if [[ ${CI_FS_MTR} == 'yes' ]]; then
    CI_FS_DOCKER_FLAG="--mount type=bind,source=/mnt/ci_disk_dir_${CMAKE_BUILD_TYPE},destination=/tmp/ci_disk_dir"
fi

if [[ ${ZEN_FS_MTR} == "yes" ]] && [[ ${WITH_ROCKSDB} == "ON" ]]; then
    if [[ ${DOCKER_OS} == "ubuntu:jammy" ]] || [[ ${DOCKER_OS} == "debian:bullseye" ]] || [[ ${DOCKER_OS} == "oraclelinux:9" ]]; then
        sudo install --owner=root --group=root --mode=+rx $SCRIPTS_DIR/nullblk-zoned /usr/bin/

        ZEN_FS_DOCKER_FLAG=''
        for nulldevice in {0..5}; do
            sudo bash -c "echo 0 > /sys/kernel/config/nullb/nullb$nulldevice/power" || true
            sudo rmdir /sys/kernel/config/nullb/nullb$nulldevice || true 

            sudo nullblk-zoned $nulldevice 512 128 124 0 32 12 12
            sudo chown 1001:1001 /dev/nullb$nulldevice
            sudo chmod 660 /dev/nullb$nulldevice
            ZEN_FS_DOCKER_FLAG+=" --device=/dev/nullb$nulldevice"
        done
    fi
fi

if [[ "${KEYRING_VAULT_MTR}" == 'yes' ]]; then
    if [[ $(docker network list | grep bridge-vault) != *bridge-vault* ]]; then
        docker network create bridge-vault
    fi

    # Bootstrap dev mode vault instances
    BOOTSTRAP_DEV_V1="$(bash $SCRIPTS_DIR/bootstrap-vault --mode=dev --version="${KEYRING_VAULT_V1_VERSION}" --alias=v1 --port="9200" --devtoken=${VAULT_V1_DEV_ROOT_TOKEN})"
    export VAULT_V1_DEV_MTR_TOKEN=$(echo "$BOOTSTRAP_DEV_V1" | grep "MTR token" | awk -F ':' '{print $2}' | xargs)

    BOOTSTRAP_DEV_V2="$(bash $SCRIPTS_DIR/bootstrap-vault --mode=dev --version="${KEYRING_VAULT_V2_VERSION}" --alias=v2 --port="9400" --devtoken=${VAULT_V2_DEV_ROOT_TOKEN})"
    export VAULT_V2_DEV_MTR_TOKEN=$(echo "$BOOTSTRAP_DEV_V2" | grep "MTR token" | awk -F ':' '{print $2}' | xargs)

    # Bootstrap prod mode vault instances
    BOOTSTRAP_PROD_V1="$(bash $SCRIPTS_DIR/bootstrap-vault --mode=prod --version="${KEYRING_VAULT_V1_VERSION}" --alias=v1 --port="9300")"
    export VAULT_V1_PROD_ROOT_TOKEN=$(echo "$BOOTSTRAP_PROD_V1" | grep "Production token" | awk -F ':' '{print $2}' | xargs)
    export VAULT_V1_PROD_MTR_TOKEN=$(echo "$BOOTSTRAP_PROD_V1" | grep "MTR token" | awk -F ':' '{print $2}' | xargs)
    sudo install --owner=1001 --group=1001 /tmp/vault.d-v1-prod/ssl/ca.pem $SOURCES_DIR/vault-prod-v1-ca.pem

    BOOTSTRAP_PROD_V2="$(bash $SCRIPTS_DIR/bootstrap-vault --mode=prod --version="${KEYRING_VAULT_V2_VERSION}" --alias=v2 --port="9500")"
    export VAULT_V2_PROD_ROOT_TOKEN=$(echo "$BOOTSTRAP_PROD_V2" | grep "Production token" | awk -F ':' '{print $2}' | xargs)
    export VAULT_V2_PROD_MTR_TOKEN=$(echo "$BOOTSTRAP_PROD_V2" | grep "MTR token" | awk -F ':' '{print $2}' | xargs)
    sudo install --owner=1001 --group=1001 /tmp/vault.d-v2-prod/ssl/ca.pem $SOURCES_DIR/vault-prod-v2-ca.pem

    VAULT_DOCKER_FLAG="--network bridge-vault"
fi

docker run --rm --shm-size=32G \
    --tmpfs /dev/shm:rw,exec,size=32G \
    --security-opt seccomp=unconfined \
    --sysctl net.ipv6.conf.lo.disable_ipv6=0 \
    --mount type=bind,source=${SOURCES_DIR},destination=/tmp/ps \
    --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
    --mount type=bind,source=${BUILD_DIR},destination=/tmp/build \
    ${CI_FS_DOCKER_FLAG} \
    ${VAULT_DOCKER_FLAG} \
    ${ZEN_FS_DOCKER_FLAG} \
    public.ecr.aws/e7j3v3n0/ps-build:${SOURCE_IMAGE} \
    sh -c "
    set -o errexit
    set -o xtrace

    mkdir /tmp/results /tmp/ps_mtr_tempdir
    export CMAKE_BUILD_TYPE='${CMAKE_BUILD_TYPE}'
    export ANALYZER_OPTS='${ANALYZER_OPTS}'
    export HOTBACKUP_TESTING='${HOTBACKUP_TESTING}'
    export TOKUDB_ENGINES_MTR='${TOKUDB_ENGINES_MTR}'
    export TOKUDB_ENGINES_MTR_ARGS='${TOKUDB_ENGINES_MTR_ARGS}'
    export MTR_ARGS='${MTR_ARGS}'
    export MTR_REPEAT='${MTR_REPEAT}'
    export MTR_SUITES='${MTR_SUITES}'
    export CI_FS_MTR='${CI_FS_MTR}'
    export WITH_PS_PROTOCOL='${WITH_PS_PROTOCOL}'
    export KEYRING_VAULT_MTR='${KEYRING_VAULT_MTR}'
    export WORKER_NO='${WORKER_NO}'
    export VAULT_V1_DEV_ADDRESS='http://vault-dev-v1:9200'
    export VAULT_V2_DEV_ADDRESS='http://vault-dev-v2:9400'
    export VAULT_V1_PROD_ADDRESS='https://vault-prod-v1:9300'
    export VAULT_V2_PROD_ADDRESS='https://vault-prod-v2:9500'
    export VAULT_V1_DEV_ROOT_TOKEN='${VAULT_V1_DEV_ROOT_TOKEN}'
    export VAULT_V2_DEV_ROOT_TOKEN='${VAULT_V2_DEV_ROOT_TOKEN}'
    export VAULT_V1_DEV_MTR_TOKEN='${VAULT_V1_DEV_MTR_TOKEN}'
    export VAULT_V2_DEV_MTR_TOKEN='${VAULT_V2_DEV_MTR_TOKEN}'
    export VAULT_V1_PROD_ROOT_TOKEN='${VAULT_V1_PROD_ROOT_TOKEN}'
    export VAULT_V2_PROD_ROOT_TOKEN='${VAULT_V2_PROD_ROOT_TOKEN}'
    export VAULT_V1_PROD_MTR_TOKEN='${VAULT_V1_PROD_MTR_TOKEN}'
    export VAULT_V2_PROD_MTR_TOKEN='${VAULT_V2_PROD_MTR_TOKEN}'
    export DOCKER_OS='${DOCKER_OS//:/-}'
    export ZEN_FS_MTR='${ZEN_FS_MTR}'
    export WITH_ROCKSDB='${WITH_ROCKSDB}'

    sudo chown mysql:mysql /tmp/build
    mv /tmp/ps/*.pem /tmp/results || true
    cp /tmp/ps/results/*.tar.gz /tmp/results

    bash -x /tmp/scripts/test-binary-parallel-mtr /tmp/results /tmp/build

    mkdir /tmp/results/log
    rsync -a --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' /tmp/results/PS/mysql-test/mtr_var /tmp/results/log
    pwd
    ls -la
    sudo tar -C /tmp/results/log -czf "ps80-test-mtr_logs-${WORKER_NO}.tar.gz" mtr_var

    sudo mv ./ps80-test-mtr_logs-${WORKER_NO}.tar.gz /tmp/ps/results/
    sudo mv /tmp/results/*.xml /tmp/ps/results/
    sudo chown $(id -u):$(id -g) /tmp/ps/results/*.xml
"
