#!/bin/sh

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/../sources; pwd -P)
SCRIPTS_DIR=$(cd $(dirname $0)/../local; pwd -P)
SOURCE_IMAGE=${1:-centos:7}

docker run --rm \
    --mount type=bind,source=${ROOT_DIR},destination=/tmp/ps \
    --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
    perconalab/ps-build:${SOURCE_IMAGE//[:\/]/-} \
    sh -c "
    set -o errexit
    set -o xtrace

    export CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    export ANALYZER_OPTS=${ANALYZER_OPTS}
    export DEFAULT_TESTING=${DEFAULT_TESTING}
    export HOTBACKUP_TESTING=${HOTBACKUP_TESTING}
    export TOKUDB_ENGINES_MTR=${TOKUDB_ENGINES_MTR}
    export MTR_ARGS=${MTR_ARGS}
    export MTR_REPEAT=${MTR_REPEAT}

    mkdir /tmp/results
    cp /tmp/ps/results/*.tar.gz /tmp/results

    bash -x /tmp/scripts/test-binary /tmp/results

    mv /tmp/results/*.xml /tmp/results/*.output /tmp/ps/results/
    chown $(id -u):$(id -g) /tmp/ps/results/*.xml /tmp/ps/results/*.output
"
