#!/bin/bash

set -o errexit

ROOT_DIR=$(cd $(dirname $0)/../sources; pwd -P)
SCRIPTS_DIR=$(cd $(dirname $0)/../local; pwd -P)
SOURCE_IMAGE=${1:-centos:7}

echo -------------------------------------------------------------------------------
echo please, run the following commands manually
echo
echo cd /tmp/ps
echo env MAKE_OPTS=-j1 /tmp/scripts/build-binary
echo
echo /tmp/ps/build directory will be created for cmake
echo -------------------------------------------------------------------------------
docker run -it --rm \
    --mount type=bind,source=${ROOT_DIR},destination=/tmp/ps \
    --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
    perconalab/ps-build:${SOURCE_IMAGE//[:\/]/-} \
    bash
