#!/bin/bash

# Build Percona Server using Docker image from "public.ecr.aws/e7j3v3n0/ps-build"
#
# usage:
#   ./docker/run-build [Docker-OS] [Work-Dir]
#
# example:
#   cd ps-build
#   ./local/checkout
#   ./docker/run-build ubuntu:jammy
#   ./docker/run-test-parallel-mtr ubuntu:jammy

set -o errexit
set -o xtrace

# decides if keep original build files or just ".tar.gz" archive
KEEP_BUILD=${KEEP_BUILD:-no}

DOCKER_OS=${1:-ubuntu:jammy}
SOURCE_IMAGE=${DOCKER_OS//:/-}

ROOT_DIR=$(cd $(dirname $0)/..; pwd -P)
SCRIPTS_DIR=$ROOT_DIR/local
SOURCES_DIR=$ROOT_DIR/sources

WORK_DIR=${2:-$ROOT_DIR/${SOURCE_IMAGE}_${CMAKE_BUILD_TYPE}}
rm -rf $WORK_DIR
mkdir $WORK_DIR

# Ensure .ccache directory exists for Docker mounting
mkdir -p "${ROOT_DIR}/.ccache"

docker run --rm \
    --cap-add SYS_PTRACE \
    --mount type=bind,source=${SOURCES_DIR},destination=/tmp/sources \
    --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
    --mount type=bind,source=${WORK_DIR},destination=/tmp/work \
    --mount type=bind,source=${ROOT_DIR}/.ccache,destination=/tmp/ccache \
    public.ecr.aws/e7j3v3n0/ps-build:${SOURCE_IMAGE} \
    sh -c "
    set -o errexit
    set -o xtrace

    export JOB_CMAKE='${JOB_CMAKE}'
    export COMPILER='${COMPILER}'
    export CMAKE_BUILD_TYPE='${CMAKE_BUILD_TYPE}'
    export ANALYZER_OPTS='${ANALYZER_OPTS}'
    export WITH_ROCKSDB='${WITH_ROCKSDB}'
    export WITH_ROUTER='${WITH_ROUTER}'
    export WITH_GCOV='${WITH_GCOV}'
    export WITH_MYSQLX='${WITH_MYSQLX}'
    export CMAKE_OPTS='${CMAKE_OPTS}'
    export MAKE_OPTS='${MAKE_OPTS}'
    export BUILD_COMMENT='${BUILD_COMMENT}'
    export TAG='${TAG}'
    export DIST_NAME='${DIST_NAME}'
    export SSL_VER='${SSL_VER}'

    # ccache environment (ensure they're exported inside container)
    export USE_CCACHE='${USE_CCACHE:-yes}'
    export CCACHE_DIR='${CCACHE_DIR:-/tmp/ccache}'
    export CCACHE_COMPRESS='${CCACHE_COMPRESS:-1}'
    export CCACHE_COMPRESSLEVEL='${CCACHE_COMPRESSLEVEL:-1}'
    export CCACHE_CPP2='${CCACHE_CPP2:-1}'
    export CCACHE_MAXSIZE='${CCACHE_MAXSIZE:-8G}'
    export CCACHE_BASEDIR='/tmp/sources'
    export DOCKER_OS='${SOURCE_IMAGE}'
    export KEEP_BUILD='${KEEP_BUILD}'

    sudo chown mysql:mysql /tmp/work /tmp/sources /tmp/sources/mysql-test/collections /tmp/sources/storage/rocksdb/rocksdb/util /tmp/sources/rocksdb/util || :
    cp -r /tmp/source_downloads /tmp/work/source_downloads

    bash -x /tmp/scripts/build-binary /tmp/work /tmp/sources

    rm -rf /tmp/work/source_downloads
    sudo chown $(id -u):$(id -g) /tmp/work /tmp/sources /tmp/sources/mysql-test/collections /tmp/sources/storage/rocksdb/rocksdb/util /tmp/sources/rocksdb/util || :
"
